name: flutter_smartlook
description: Smartlook SDK wrapper for Flutter. Analyze user behavior in ways never possible before.
version: 4.1.25
homepage: https://www.smartlook.com/

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  vector_math: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.0

flutter:
  plugin:
    platforms:
      android:
        package: com.Smartlook.Smartlook.flutter_smartlook
        pluginClass: SmartlookPlugin
      ios:
        pluginClass: SmartlookPlugin

  assets:
   - lib/smartlook.png
